### ISSUE TITLE
How to use C++ API to do bufferMapAsync()

### ISSUE THREAD

**Issue by sleeplessai** [eliemichel/LearnWebGPU#31]
https://eliemichel.github.io/LearnWebGPU/basic-3d-rendering/input-geometry/playing-with-buffers.html#mapping-context

Hi, @eliemichel 
What is the right way to use `buffer.mapAsync` with a lambda syntax.
Please give me some examples. I've tried to replace directly with the C-api version, but it ended up with fails.
I want to use map perhaps like `buffer2.mapAsync(MapMode::Read, 0, 32, [](...) {...})` , please give me some help.

**Comment by eliemichel** [comment]
Hey, sorry for not replying earlier! You can find an example [here in WebGPU-C++ readme](https://github.com/eliemichel/WebGPU-Cpp#capturing-closures) (although I should update it :o ).

```C++
auto h = buffer.mapAsync(MapMode::Read, 0, 16, [&](wgpu::BufferMapAsyncStatus status) {
	std::cout << "Buffer mapped with status " << status << std::endl;
	const unsigned char* bufferData = (const unsigned char*)buffer.getConstMappedRange(0, 16);
	std::cout << "bufferData[0] = " << (int)bufferData[0] << std::endl;
	buffer.unmap();
});
```

Note that the `auto h` handle returned by the mapping operation must remain in scope until the callback gets called. This is needed to ensure that the context captured by the lambda still exists (and thus not needed for captureless lambdas).
