### ISSUE TITLE
Missing instruction to update required limits

### ISSUE THREAD

**Issue by jinhwanlazy** [eliemichel/LearnWebGPU#35]
Hi @eliemichel, thanks for the great tutorial. 

While I was following the [Depth buffer chapter,](https://github.com/eliemichel/LearnWebGPU/blob/0f7f139f1a3dbba8e4b9ce8bec17e0a672b85a17/basic-3d-rendering/3d-meshes/depth-buffer.md) I found some missing instructions to [update requiredLimits](https://github.com/eliemichel/LearnWebGPU-Code/blob/df830031567399457356355761e7f96b100f6404/main.cpp#L105C1-L108C50), which cost me some time to debug.

**Comment by eliemichel** [comment]
My apologies! Thanks a lot for reporting, this is now fixed :)
