### ISSUE TITLE
Swapchain instructions removed from webgpu API

### ISSUE THREAD

**Issue by Fabxx** [eliemichel/LearnWebGPU#46]
The "first color" chapter mentions the creation of a swap chain descriptor and such, but in the API those functions have been totally removed. Update the chapter when possible

**Comment by eliemichel** [comment]
I started working on it, but for now as you can see in [`dawn.json`](https://dawn.googlesource.com/dawn/+/refs/heads/main/dawn.json) the Dawn backend did not switch to this new API yet, so I'm waiting for them.

**Comment by eliemichel** [comment]
Since a couple of days, emscripten finally supports the new Surface config API, so this was upgraded
