### ISSUE TITLE
There are 16 vertices in pyramid.txt

### ISSUE THREAD

**Issue by IvaKom** [eliemichel/LearnWebGPU#58]
https://github.com/eliemichel/LearnWebGPU/blob/cfae8204a1a6746a1a90f671fa0edfdfd368fbfb/basic-3d-rendering/3d-meshes/basic-shading.md?plain=1#L177
https://github.com/eliemichel/LearnWebGPU/blob/cfae8204a1a6746a1a90f671fa0edfdfd368fbfb/basic-3d-rendering/3d-meshes/basic-shading.md?plain=1#L66..L88

**Comment by eliemichel** [comment]
Indeed, thx!
