### ISSUE TITLE
macos protobuf dependency

### ISSUE THREAD

**Issue by pentallelogram** [eliemichel/LearnWebGPU#62]
```
learnwebgpu/build/_deps/dawn-src/third_party/libprotobuf-mutator/src/port/protobuf.h:20:10: fatal error: 'google/protobuf/any.pb.h' file not found
#include "google/protobuf/any.pb.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
```

The version of dawn included with this project is based on `chromium/6512` but was giving me build difficulties. I think it's expecting me to have protobuf headers which I don't have and didn't want to install. I saw [this commit](https://github.com/google/dawn/commit/0c27cf20244a067b751e5c0fc49aedd840962af0) and figured it was something someone at google ran into and fixed. So I changed the `webgpu/cmake/FetchDawn.cmake` file to a newer tag like this:

```
     DOWNLOAD_COMMAND
         cd ${FETCHCONTENT_BASE_DIR}/dawn-src &&
         git init &&
         git fetch --depth=1 https://dawn.googlesource.com/dawn chromium/6536 &&
         git reset --hard FETCH_HEAD
```

tag `chromium/6536` seems to work successfully for me. Maybe it's a good idea to either update the script to install the protobuf headers or to update the dawn project fetch tag like I did.

Thanks for the tutorials!

**Comment by sshsphere** [comment]
Same issue here on windows, seems to be new. Can also confirm your fixed worked for me aswell

**Comment by eliemichel** [comment]
Thanks for the feedback! I think I'll upgrade dawn distrib then

**Comment by eliemichel** [comment]
Dobe.
