### ISSUE TITLE
Update favicon module name in config

### ISSUE THREAD

**Issue by tcmetzger** [eliemichel/LearnWebGPU#7]
Thanks for using [Sphinx Favicon](https://github.com/tcmetzger/sphinx-favicon) in your project! I just released version 1.0 of the extension, which brings one breaking change: to better conform with Python standards, we changed the module name to `sphinx_favicon` (instead of `sphinx-favicon`). This means you'll have to update your conf.py file to use version 1.0. Otherwise, your existing configuration should continue to work!

**Comment by eliemichel** [comment]
Fixed in 229b5bfae4df4d695a96096ad99d97cc49d29561, thanks a lot for letting me know!
