### ISSUE TITLE
Broken link to resulting code in "A first uniform"

### ISSUE THREAD

**Issue by EricGrange** [eliemichel/LearnWebGPU#76]
At the bottom of https://eliemichel.github.io/LearnWebGPU/basic-3d-rendering/shader-uniforms/a-first-uniform.html#
the link to resulting code "step039-vanilla" goes to https://github.com/eliemichel/LearnWebGPU-Code/tree/step039-vanilla which is a 404

**Comment by eliemichel** [comment]
There is now a step039-vanilla branch in the code repo! I'm adding these progressively, I know many vanilla examples are missing, but there should be one for all the chapters marked with a **green light** 🟢!

**Comment by EricGrange** [comment]
Thanks for your work!
