### ISSUE TITLE
Is Emscripten's WebGPU implementation currently limited to desktop browsers only?

### ISSUE THREAD

**Issue by L1uyu** [eliemichel/LearnWebGPU#85]
I tested several chapters on Android Chrome 131 and iOS 18.2 Safari with the WebGPU flag enabled. Both browsers displayed the error: 'Could not get WebGPU adapter: WebGPU not available on this browser.'
Is this a limitation of the current Emscripten version, or am I missing some configuration settings?

**Comment by eliemichel** [comment]
As far as I can tell, it is rather a limitation of the Android/iOS version of the browser (maybe specific to your device). A quick check is to try and get a WebGPU adapter in JavaScript with `navigator.gpu.requestAdapter()` in the browser's dev console (if you can connect one to your device). It's probably not specific to emscripten! Or if it is, then you could probably work it around with a few lines of JavaScript glue.

**Comment by eliemichel** [comment]
No worry! I had not noticed this need for https (I guess I always use it), thanks for pointing it out!
